### ISSUE TITLE
Problem with location of ProjectSettingsToolbar folder

### ISSUE THREAD

**Issue by uvivagabond** [baba-s/project-settings-toolbar#1]
Hi,
actually I must put ProjectSettingsToolbar folder as a root in Project window. Path to textures is constant so when I put ProjectSettingsToolbar folder in other folder then buttons have lost textures.

It could be fixed like this:
![toolbar](https://user-images.githubusercontent.com/20247639/36611115-b8fe092e-18d2-11e8-8dc2-3b41aaab4b06.png)

**Comment by baba-s** [comment]
Hi, I solved this problem. The code looks like this. Thank you!

```cs
var path = string.Format( "{0}/Textures/{1}.png", m_dir, command );

...

private void OnEnable()
{
    var mono = MonoScript.FromScriptableObject( this );
    var path = AssetDatabase.GetAssetPath( mono );
    m_dir = Path.GetDirectoryName( path );
}
```
